#!/bin/sh
#
#  THis script will:
#
#   1.  Either checkout a fresh copy of symbiosis
#
#   2.  Update an existing copy
#
#  These will happen every time it runs, and if we've not built packages
# with the current hg identifier it will trigger a build by executing
# the  auto-builder script.
#
# Steve
# -- 
#

REPO=Symbiosis
SRC=https://projects.bytemark.co.uk/hg/$REPO
DST=$HOME/$REPO
LOCK=$DST/$REPO-builder.lck

LOGFILE=$DST/$REPO-builder.$$.log
ERRFILE=$DST/$REPO-builder.$$.err
MAILTO="patrick@bytemark.co.uk"


#
# Exit on errors
#
set -e

#
# Here is where we mail the LOGFILE
#
cleanup() {
  trap - ERR TERM HUP INT QUIT EXIT

  #
  # Mail the error file if it is non-zero in size
  #
  if [ -s "${ERRFILE}" ] ; then
    # Symlink it.
    ln -sf $ERRFILE $DST/$REPO-builder.current.err
    # And mail it
    mail -e -s "${REPO} build error on $(date +"%Y-%m-%d %H:%M:%S")" ${MAILTO} < "${ERRFILE}"
  else
    rm -f "${ERRFILE}"
  fi

  rm -f "${LOCK}"
}

#
# Make sure our destination exists
#
if [ ! -d $DST ] ; then
	mkdir -p $DST
fi

#
# Make sure we don't run more than once
#
if [ -e $LOCK ] ; then
	echo "$0 is already running"
	exit 0
fi

trap cleanup ERR TERM HUP INT QUIT EXIT

touch $LOCK

ID=`hg id -i -r tip $SRC`

#
# If this revision is already checked out, then we can exit.
#
if [ -d $DST/$ID ]; then
	exit 0
fi

#
# OK create the logfile
#
touch $LOGFILE 
#
#
# Symlink the logfile.
ln -sf $LOGFILE $DST/$REPO-builder.current.log

#
# Get on with the real work
#
echo "Cloning $REPO" >> $LOGFILE 2>> $ERRFILE
cd $DST 

#
# Clone the repo
# 
hg clone $SRC $ID    >> $LOGFILE 2>> $ERRFILE
#
#
rm -f $DST/current
ln -s $DST/$ID $DST/current

cd $DST/$ID
rake clobber      >> $LOGFILE 2>> $LOGFILE
rake upload       >> $LOGFILE 2>> $LOGFILE 

cd $DST/$ID/build-utils
./auto-test   >> $LOGFILE 2>> $ERRFILE

#
# Copy the LOGFILE in place.
# 
if [ -e $HOME/htdocs/current ] ; then
	cp $LOGFILE $HOME/htdocs/current/$REPO-builder.log

  # Copy over the error file if needed.
	[ -s $ERRFILE ] && cp $ERRFILE $HOME/htdocs/current/$REPO-builder.err
fi


