#!/bin/sh

#
# This just provisions a machine for each distro / architecture.
# 

passwd=`pwgen -n 10`

echo "Root password is $passwd" 

for arch in i386 amd64 ; do
        for distro in lvhost symbiosis ; do

                #
                # If we already have an image, carry on.
                #
                if [ -d /shared/images/symtester/$distro/$arch/run ] ; then
                  echo Image for symtester/$distro/$arch already exists
                  continue
                fi

                #
                #  If the guest exists.
                #
                if [ -d /shared/guests/symtester/ ]; then
                  sudo km delete symtester
                fi

                #
                #  Recreate
                #
                sudo km-provision --pass=$passwd  --ip=89.16.160.206 \
                             --name=symtester --arch=$arch \
                             --key=$HOME/.ssh/id_rsa.pub \
                             --imager=http://imager3.bytemark.co.uk:5000 \
                             --dist=$distro \
                             --nostart

                sudo cp -R /shared/guests/symtester/* /shared/images/symtester/$distro/$arch
        done
done
