#!/bin/bash

#
# This just provisions a machine for each distro / architecture.
# 

passwd=`pwgen -n 10`

echo "Using guest ${GUESTNAME:=symtester}"

echo "Root password is $passwd" 

for arch in i386 amd64 ; do
        for distro in lvhost symbiosis ; do

                #
                # If we already have an image, carry on.
                #
                if [ -d /shared/images/$GUESTNAME/$distro/$arch/run ] ; then
                  echo Image for $GUESTNAME/$distro/$arch already exists
                  continue
                fi

                #
                #  If the guest exists.
                #
                if [ -d /shared/guests/$GUESTNAME/ ]; then
                  sudo km delete $GUESTNAME
                fi

                #
                #  Recreate
                #
                sudo km-provision --pass=$passwd  --ip=89.16.160.206 \
                             --name=$GUESTNAME --arch=$arch \
                             --key=$HOME/.ssh/id_rsa.pub \
                             --imager=http://imager3.bytemark.co.uk:5000 \
                             --dist=$distro \
                             --nostart

                sudo cp -R /shared/guests/$GUESTNAME/* /shared/images/$GUESTNAME/$distro/$arch
        done
done
