#!/bin/bash

set -e

BUILDER=${BUILDER:-symbiosis-builder.sh.bytemark.co.uk}

#
# Make sure we're up to date
#
echo "Doing first upgrade..."
if [ -x /usr/bin/bytemark-vhost-updater ] ; then

	echo -e "SUDO_USER=\"root\"\nEMAIL=\"\"\nQUIET=\"\$OPTIONS\"" >> /etc/update-packages.conf
	/usr/bin/bytemark-vhost-updater

elif [ -x /usr/bin/symbiosis-updater ] ; then

	echo -e "SSH_TTY=\"\"\nEMAIL=\"\"\nQUIET=\"\$OPTIONS\"" >> /etc/symbiosis/updater
	/usr/bin/symbiosis-updater

fi 

echo "Changing package lists..."
#
# Now change the package lists
#
sed -i -e "s#http://\(vhost\|symbiosis\).bytemark.co.uk/[^ ]\+#http://$BUILDER/lenny/current#g" /etc/apt/sources.list{,.security}

echo "Doing second upgrade..."
#
# And update again.
#
if [ -x /usr/bin/bytemark-vhost-updater ] ; then

	/usr/bin/bytemark-vhost-updater

elif [ -x /usr/bin/symbiosis-updater ] ; then

	/usr/bin/symbiosis-updater

fi 

