#!/bin/sh
#
#  This script is a thin wrapper around "debuild", which has the
# following changes:
#
#   * Doesn't sign anything.
#   * Doesn't complain about the lack of an .orig.tar.gz file.
#   * Moves the result into ../output/
#
# Steve
# --

debuild  --post-dpkg-buildpackage-hook="$(pwd)/../build-utils/move-changes %p %v"  --no-tgz-check -sa -us -uc
