#!/usr/bin/ruby 

require 'bytemark/vhost/monitor/check'

class FreshclamCheck < Bytemark::Vhost::Monitor::Check

  def initialize
    super
    @process.pidfile = "/var/run/clamav/freshclam.pid"
    @process.initscript = "/etc/init.d/clamav-freshclam"
    @name = "freshclam"
  end

  def do_check
    return SystemExit::EX_CONFIG unless initscript_ok?

    r = do_process_check
    if SystemExit::EX_TEMPFAIL == r 
      should_be_running ? self.start : self.stop
    end
    return r
  end

  def should_be_running
    (0 < Dir.glob('/srv/*/config/antivirus').length)
  end
end

exit FreshclamCheck.new.do_check if $0 == __FILE__

