#!/usr/bin/ruby
#
require 'symbiosis/monitor/check'

# Checks that the cron service is running
class CronCheck < Symbiosis::Monitor::Check
  def initialize
    super unit_name: 'cron',
          pid_file: '/var/run/crond.pid',
          init_script: '/etc/init.d/cron'
  end
end

exit CronCheck.new.do_check if $PROGRAM_NAME == __FILE__
