#!/usr/bin/ruby 
#
require 'bytemark/vhost/monitor/check'

class CronCheck < Bytemark::Vhost::Monitor::Check

  def initialize
    super
    @process.pidfile = "/var/run/crond.pid"
    @process.initscript = "/etc/init.d/cron"
    @name = "cron"
  end

  def do_check
    return SystemExit::EX_CONFIG unless initscript_ok?

    r = do_process_check
    self.start if SystemExit::EX_TEMPFAIL == r 

    return r
  end

end

exit CronCheck.new.do_check if $0 == __FILE__

 
