#!/usr/bin/ruby 

require 'bytemark/vhost/monitor/check'

class Exim4Check < Bytemark::Vhost::Monitor::Check

  def initialize
    super
    @process.pidfile = "/var/run/exim4/exim.pid"
    @process.initscript = "/etc/init.d/exim4"
    @name = "exim4"
  end

  def do_check
    return SystemExit::EX_CONFIG unless initscript_ok?

    tcpconnection = Bytemark::Vhost::Monitor::TCPConnection.new(
      "localhost",
      "smtp",
      [nil, "EHLO localhost\r\n", nil, "QUIT\r\n", nil] )
    r = do_tcpconnection_check(tcpconnection)
    self.restart if SystemExit::EX_TEMPFAIL == r
    return r
  end

  def do_tcpresponse_check(responses)
    bad = responses.find{|l| l !~ /^2\d+[ -]/}
    raise "Unexpected response '#{bad}'" unless bad.nil? 
  end

end

exit Exim4Check.new.do_check if $0 == __FILE__

