#!/usr/bin/ruby 
#
require 'symbiosis/monitor/check'

class PureAuthdCheck < Symbiosis::Monitor::Check

  def initialize
    super
    @process.pidfile = "/var/run/pure-ftpd/pure-authd.pid"
    @process.initscript = "/etc/init.d/pure-authd"
    @name = "pure-authd"
  end

  def do_check
    return SystemExit::EX_CONFIG unless initscript_ok?

    r = do_process_check
    if SystemExit::EX_TEMPFAIL == r 
      should_be_running ?  self.start : self.stop
    end
    return r
  end

end

exit PureAuthdCheck.new.do_check if $0 == __FILE__

 
