#!/usr/bin/ruby 

require 'symbiosis/monitor/check'

class SshdCheck < Symbiosis::Monitor::Check

  def initialize
    super
    @process.pidfile = "/var/run/sshd.pid"
    @process.initscript = "/etc/init.d/ssh"
    @name = "sshd"
  end

  def do_check
    return SystemExit::EX_CONFIG unless initscript_ok?

    tcpconnection = Symbiosis::Monitor::TCPConnection.new(
      "localhost", "ssh", [nil,"SSH-2.0-OpenSSH-4.3p2\n"]
    )
    r = do_tcpconnection_check(tcpconnection)
    self.restart if SystemExit::EX_TEMPFAIL == r
    return r
  end

  def do_response_check(responses)
    raise "Unexpected response '#{responses.first}'" unless responses.first =~ /^SSH/
  end

end

exit SshdCheck.new.do_check if $0 == __FILE__

