#!/usr/bin/ruby

require 'symbiosis/monitor/check'

class MysqldCheck < Symbiosis::Monitor::Check

  def initialize
    super
    @process.pidfile = "/var/run/mysqld/mysqld.pid"
    @process.initscript = "/etc/init.d/mysql"
    @name = "mysqld"
  end

  def do_check
    return SystemExit::EX_CONFIG unless initscript_ok?

    r = do_process_check
    self.restart if SystemExit::EX_TEMPFAIL == r
    return r unless 0 == r

    debian_conf = "/etc/mysql/debian.cnf"
    if not File.readable?(debian_conf)
      puts "Unable to test connection, as #{debian_conf} is not readable"
      return SystemExit::EX_NOPERM
    end
    begin
      puts "Testing connection with a ping"
      cmd = "mysqladmin --defaults-extra-file=#{debian_conf} -u debian-sys-maint ping 2>&1"
      Kernel.system(cmd)
      if $?.success?
        puts "Connection tested OK."
        return SystemExit::EX_OK
      else
        puts "Connection test failed."
        self.restart
        return SystemExit::EX_TEMPFAIL
      end
    rescue => err
      puts "Connection test failed permanently."
      return SystemExit::EX_UNAVAILABLE
    end
  end

end

exit MysqldCheck.new.do_check if $0 == __FILE__
