#!/bin/bash

#
# Hash password "semiconscious malpractice" and store in .mysql.hash file
#

echo "semiconscious malpractice" | ruby -n -rdigest -e \
  'puts Digest::SHA1.hexdigest(Digest::SHA1.digest($_.chomp)).upcase' > \
    /etc/first-boot.d/.mysql.hash
chmod 0600 /etc/first-boot.d/.mysql.hash

