#!/bin/bash
#

set -e

PREFIX=$(dirname ${0})

dpkg --clear-avail

if [ -f $PREFIX/conf/action ] ; then
  ACTION=$(< ${PREFIX}/conf/action)
fi

CONF=$PREFIX/conf-$DEBIAN_RELEASE
OLD_CONF=$PREFIX/conf-$OLD_DEBIAN_RELEASE

DEBIAN_FRONTEND=noninteractive
export DEBIAN_FRONTEND

APT_OPTS="-q -y -o DPkg::Options::=--force-confdef -o DPkg::Options::=--force-confnew --quiet"
APT_LIST=/etc/apt/sources.list.d/symbiosis.list
# description of actions:
# install - fresh install latest from a stretch base
# upgrade - upgrade to latest from a symbiosis-stretch base
# dist-upgrade - upgrade to latest from symbiosis-jessie

do_upgrade() {
  echo "I: seed debconf"
  debconf-set-selections < "$1/debconf-preseed"

  echo "I: perform update"
  apt-get $APT_OPTS update

  echo "I: perform $2"
  if [ "$2" = "install" ] ; then
    apt-get $APT_OPTS install $(< $1/packages)
  else
    apt-get $APT_OPTS $2
  fi
}

if [ "upgrade" = "$ACTION" ] ; then
  echo "I: Install current symbiosis.bytemark.co.uk release"
  echo "deb http://symbiosis.bytemark.co.uk/$DEBIAN_RELEASE/ ./" > $APT_LIST

  do_upgrade $CONF install

elif [ "dist-upgrade" = "$ACTION" ] ; then
  echo "I: Install $OLD_DEBIAN_RELEASE version of Symbiosis from symbiosis.bytemark.co.uk"
  echo "deb http://symbiosis.bytemark.co.uk/$OLD_DEBIAN_RELEASE/ ./" > $APT_LIST

  do_upgrade $OLD_CONF install

  sed -e "s/$OLD_DEBIAN_RELEASE/$DEBIAN_RELEASE/g" -i /etc/apt/sources.list
fi

echo "I: $ACTION $BRANCH_NAME version of Symbiosis from repo.bytemark.co.uk"
cp $CONF/sources.list $APT_LIST
echo "deb http://repo.bytemark.co.uk/open-source/symbiosis/$BRANCH_NAME/latest/ ./" >> $APT_LIST

do_upgrade $CONF $ACTION
