require 'digest/md5'
require 'erb'
require 'tempfile'

#
# This class is used to make configuration files easier to handle.
#
# The idea is that we write an MD5 sum to the file in a parseable way, and then
# check that to see if it has changed, or not.
#
module Symbiosis

  class ConfigFile

    attr_reader :comment_char, :filename

    def initialize(filename, comment_char="#")
      @filename = filename
      @comment_char = comment_char
      @contents = nil
    end

    #
    # Template the configuration
    #
    def generate_config( template )
      #
      # Read the template file.
      #
      content = File.open( template, "r" ).read()

      #
      # Create a template object, and add a newline for good measure.
      #
      config = ERB.new( content ).result( binding ) + "\n"

      #
      # Return our template + MD5.
      #
      return config + [comment_char,"Checksum MD5",Digest::MD5.new(config).hexdigest].join(" ")
    end

    #
    # Write the configuration
    #
    def write(config = self.generate_config)
      File.open(self.filename,"w+") do |fn|
        fn.write(config)
      end

      self.filename
    end


    #
    # See if the generated config is OK
    #
    def test(filename)
      true
    end

    #
    # Does the configuration need updating
    #
    def outdated?
      false
    end


    #
    # This tests to see if the configuration has been altered.
    #
    def changed?
      #
      # Read the snippet
      #
      snippet = File.readlines(self.filename)
      
      #
      # We expect the checksum to be the last line of the file
      #
      if snippet.last.chomp =~ /^#{comment_char} Checksum MD5 ([a-f0-9]{32,32})$/
        #
        # OK we've found the checksum
        #

        supposed_checksum = $1

        #
        # Pop off the last line, as this isn't part of the checksum
        #
        snippet.pop
        
        #
        # And compare to the calculated checksum of the rest of the snippet
        #
        return Digest::MD5.new(snippet.join).hexdigest != supposed_checksum
      
      #
      # We're OK if the file has a big warning in it.
      #
      elsif snippet.any?{|l| comment_char+" DO NOT EDIT THIS FILE - CHANGES WILL BE OVERWRITTEN" == l.chomp}
        #
        # So return true
        #
        return false

      end

      #
      # Assume the file has been edited.  
      #
      puts "\tCould not find checksum or big warning." if $VERBOSE

      true
    end

  end

end

