#!/bin/bash
#
#  Update the local system with apt-get so that all pending
# package update are completed.
#
#  This uses a special sources.list file to ensure that we only
# update packages that we expect to update.
#
#  See full manpage at the foot of this script.
#
# Steve
# --


#
#  PATH updating
#
PATH=/sbin:/usr/sbin:/bin:/usr/bin
export PATH


#
#  The sources list we update from.
#
SOURCES="/etc/apt/sources.list.security"


#
#  The email address to notify, if any.
#
EMAIL=automatic@lists.bytemark.co.uk


#
#  Minimise debconf front-end
#
DEBIAN_FRONTEND=noninteractive
export DEBIAN_FRONTEND


#
#  The options to use by default.
#
OPTIONS="-o \"APT::Get::AllowUnauthenticated=true\" -o \"DPkg::Options::=--force-confold\" -o \"Dir::Etc::SourceList=$SOURCES\"  -o \"Dir::Etc::SourceParts=/dev/null\""


#
#  Options to use for operations that should be quiet.
#
QUIET="-o quiet=2 $OPTIONS"


#
#  Upgrade method [dist-upgrade|upgrade]
#
METHOD="dist-upgrade"



#
#  Source a config file if it exists, that'll allow
# the settings above to be overridden.
#
if [ -e /etc/symbiosis/updater ]; then
    . /etc/symbiosis/updater
fi


#
#  Exit silently if we shouldn't run - this is configured
# via "DISABLED=1" in /etc/symbiosis/updater
#
if [ ! -z "$DISABLED" -a "$DISABLED" ];  then
    exit
fi


#
#  Sanity check that we're on a Debian/Ubuntu host.
#
if [ ! -x /usr/bin/apt-get ] ; then
    echo "/usr/bin/apt-get missing or non-executable."
    exit
fi


#
#  Make sure we have our sources.list present.
#
if [ ! -e "$SOURCES" ] ; then
    echo "$SOURCES missing"
    exit
fi


#
#  Make sure we're root
#
if [ "$UID" -ne "0" ] ; then
    echo "You're not root."
    exit
fi


#
# Mark ourself as running to avoid monit issues.
#
touch /var/tmp/update.packages


#
# Sleep a random amount of time, max ten minutes, unless running under sudo.
#
if [ ! -z "$SSH_TTY" ]; then
    splay=$RANDOM

    #
    # modulo: Which is why we have /bin/bash in the
    # shebang line of thie script.
    #
    MAXSLEEP=600
    let "splay %= $MAXSLEEP"

    sleep $splay
fi



#
#  Update our sources list
#
apt-get $QUIET update 2>/dev/null >/dev/null


#
#  Now simulate a dist-upgrade so that we can see if we need to do anything
#
tmp=`tempfile`
/usr/bin/apt-get $QUIET --simulate $METHOD &>"$tmp"


#
#  Did that require us to upgrade?
#
if ( grep ^Inst "$tmp" 2>/dev/null >/dev/null ) ; then


    #
    #  We're going to update now - overwrite the temporary file
    # with the output of the upgrade
    #
    /usr/bin/apt-get $OPTIONS --yes --force-yes -u $METHOD &>"$tmp"

    #
    #  Send output by email if we have an email address setup
    # and mailx available.
    #
    if ( test ! -z "$EMAIL" -a -x /usr/bin/mailx ); then

        cat "$tmp" | /usr/bin/mailx -s "[update-packages] `hostname`" "$EMAIL"

    else
        cat "$tmp"
    fi
fi



#
# Make sure we have an archive directory.
#
if [ ! -d /var/log/update-packages ]; then
    mkdir -p /var/log/update-packages
fi

#
# Move the temporary file somewhere safe
#
if [ -s "$tmp" ]; then

    # date foramt
    now=`date +%d-%m-%Y-%T`

    #
    #  Move it into place.
    #
    mv "$tmp" "/var/log/update-packages/$now"
    chmod 644 "/var/log/update-packages/$now"
else

    rm -f "$tmp"
fi


#
# Remove our lockfile
#
if [ -e /var/tmp/update.packages ]; then
    rm -f /var/tmp/update.packages
fi


exit


#
#  This is POD for the manpage creation.
#
cat<<EOF

=head1 NAME

symbiosis-updater - Apply security and other package updates

=cut

=head1 SYNOPSIS

  symbiosis-updater [args]

=cut


=head1 ABOUT

This script is designed to run non-interactively and apply any pending
security and system package updates, using the Debian apt-get system.

The script will read a special sources list file which will contain
references to repositories which may be upgraded.

By default the script will archive the results of its upgrades

=cut

=head1 DISABLING

To disable the updater please run the following command:

=for example begin

echo "DISABLED=1" >> /etc/symbiosis/updater

=for example end

This will ensure the updater exits.

=cut

=head1 FILES

The system will invoke B<apt-get> against the file
B</etc/apt/sources.list.security> and archive the results of any updates
applied to the directory B</var/log/symbiosis-updater/>

=cut

=head1 BUGS

None known.

=cut

=head1 AUTHOR

 Steve
 --

=cut

=head1 LICENSE

Copyright (c) 2008-2010 by Bytemark Computer Consulting Ltd.
All rights reserved.

This program is free software;
you can redistribute it and/or modify it under
the same terms as Perl itself.
The LICENSE file contains the full text of the license.

=cut

EOF
