#!/bin/sh

set -e

if [ "$1" = "upgrade" ] ; then
  #
  #  Do nothing for upgrades.
  #
  echo "I: Skipping removal."
  exit 0
fi

#
# Replace 000-default site
#
if [ -e /etc/apache2/sites-available/000-default.conf -a ! -e /etc/apache2/sites-enabled/000-default.conf ] ; then
  echo "I: enabling site 000-default"
  ln -s /etc/apache2/sites-available/000-default.conf /etc/apache2/sites-enabled/000-default.conf
fi

#
# Remove the serve-cgi snippet (ugh!)
#
if [ -e /etc/apache2/conf-available/serve-cgi-bin.conf -a ! -e /etc/apache2/conf-enabled/serve-cgi-bin.conf ] ; then
  echo "I: enabling conf serve-cgi-bin"
  ln -s /etc/apache2/conf-available/serve-cgi-bin.conf /etc/apache2/conf-enabled/serve-cgi-bin.conf
fi

if [ -e /usr/share/apache2/apache2-maintscript-helper ] ; then

  . /usr/share/apache2/apache2-maintscript-helper

  #
  # Disable the modules we enabled
  #
  for mod in headers rewrite cgi ssl ; do
    apache2_invoke dismod $mod
  done

  for site in zz-mass-hosting zz-mass-hosting.ssl ; do
    apache2_invoke dissite $site
  done
fi

#DEBHELPER#

exit 0
