#!/usr/bin/ruby
#
require 'symbiosis/monitor/check'

# ensure that Incrond is running
class IncrondCheck < Symbiosis::Monitor::Check
  def initialize
    super pid_file: '/var/run/incrond.pid',
          init_script: '/etc/init.d/incron',
          unit_name: 'incrond'
  end
end

exit IncrondCheck.new.do_check if $PROGRAM_NAME == __FILE__
