#!/bin/sh

set -e

#
# Skip, if we are not in "configure" state
#
if [ "$1" != "configure" ]; then
        echo "I: Skipping configuration"
        exit 0
fi


#
#  Remove old files
#
for i in phpmyadmin.vhost.conf phpadmin.conf phpmyadmin.conf ; do
  if [ -e /etc/apache2/conf.d/$i ]; then
    rm -f /etc/apache2/conf.d/$i
  fi
done


#
#  Ensure that the PHPMyAdmin configuration file is included.
#
if [ -e /etc/phpmyadmin/apache.conf ]; then
    ln -sf /etc/phpmyadmin/apache.conf /etc/apache2/conf.d/phpmyadmin.conf
fi

#
#  Restart Apache2 to ensure this change is picked up.
#
if which invoke-rc.d >/dev/null 2>&1; then
    invoke-rc.d apache2 restart
else
    /etc/init.d/apache2 restart
fi

#DEBHELPER#
exit 0
