#!/bin/bash

set -e

#
# Skip, if we are not in "configure" state
#
if [ "$1" != "configure" ]; then
        echo "I: Skipping configuration"
        exit 0
fi


#
#  Remove old files
#
for i in phpmyadmin.vhost.conf phpadmin.conf phpmyadmin.conf ; do
  if [ -e /etc/apache2/conf.d/$i ]; then
    rm -f /etc/apache2/conf.d/$i
  fi
done


#
#  Ensure that the PHPMyAdmin configuration file is included.
#
if [ -e /etc/phpmyadmin/apache.conf ]; then
    ln -sf /etc/phpmyadmin/apache.conf /etc/apache2/conf.d/phpmyadmin.conf
fi

#
#  Append HTTP basic auth
#
if [ -e /etc/phpmyadmin/config.inc.php ]; then

    if ( ! grep Symbiosis-Auth /etc/phpmyadmin/config.inc.php >/dev/null 2>/dev/null ); then
        cat >>/etc/phpmyadmin/config.inc.php <<EOF

//
//  This setting uses HTTP BasicAuth rather than cookies for
// authentication, this is more sane in the presence of remote
// attackers probing your server.
//
//  Symbiosis made this change.
//
//  Symbiosis-Auth
//
\$cfg['Servers'][\$i]['auth_type'] = 'http';
EOF
    fi
    #
    # change cookie auth to http, everywhere.  This is to catch the configuration section used when dbconfig-common is used to configure the database.
    #
    sed  -i -e "s/^\([ \t]*\$cfg\[[\"']Servers[\"']\]\[\$i\]\[[\"']auth_type[\"']\][ \t]*=[ \t]*[\"']\)cookie\(['\"];\)/\1http\2/" /etc/phpmyadmin/config.inc.php
fi


#
#  Force SSL
#

if [ -e /etc/phpmyadmin/config.inc.php ]; then
    if ( ! grep Symbiosis-SSL /etc/phpmyadmin/config.inc.php >/dev/null 2>/dev/null ); then
        cat >>/etc/phpmyadmin/config.inc.php <<EOF

//
// This flag mandates the use of SSL for phpmyadmin
//
// Symbiosis made this change.
//
// Symbiosis-SSL
//
\$cfg['ForceSSL'] = true;
EOF
    fi
fi



#
#  Restart Apache2 to ensure this change is picked up.
#
if which invoke-rc.d >/dev/null 2>&1; then
    invoke-rc.d apache2 force-reload || true
else
    /etc/init.d/apache2 force-reload || true
fi

#DEBHELPER#
exit 0
