#!/usr/bin/ruby

require 'symbiosis/monitor/check'

# ensure prosody is running
class ProsodyCheck < Symbiosis::Monitor::Check
  def initialize
    super pid_file: '/var/run/prosody/prosody.pid',
          init_script: '/etc/init.d/prosody',
          unit_name: 'prosody',
          process_name: 'lua5.1'
  end

  def should_be_running?
    !Dir.glob('/srv/*/config/xmpp').empty?
  end
end

exit ProsodyCheck.new.do_check if $PROGRAM_NAME == __FILE__
