#!/bin/sh -eu

if ! [ "$1" = "live-update" ] ; then
   echo "I: $0: Ignoring unknown hook action $1"
   exit 0
fi

#
# Reconfigure httpd regardless of the domains given.
#
exec /usr/bin/sudo /usr/sbin/symbiosis-httpd-configure
