#!/usr/bin/ruby
#
# NAME
#
#   create-ssl-sites -- Auto-configure SSL sites
#
# SYNOPSIS
#
#  General Options:
#
#   --force       Force the re-creation of all SSL sites.
#   --template    Specify an alternative template file to read.
#
#  Help Options:
#
#   --help        Show the help information for this script.
#   --verbose     Show debugging information.
#
# DETAILS
#
#   This script is designed to iterate over the domains hosted
#  upon a Symbiosis system, and configure Apache to listen appropriate
#  when a domain is configured for SSL hosting and not yet configured.
#
# AUTHOR
#
#   Steve Kemp <steve@bytemark.co.uk>
#


require 'erb'
require 'getoptlong'
require 'symbiosis/domains'
require 'symbiosis/domain/ssl'
require 'symbiosis/config_files/apache_ssl'


#
#  Entry point to the code
#
$FORCE    = false
$HELP     = false
$VERBOSE  = false

#
#  Do we need to restart apache?
#
$RESTART=false

#
# The root directory -- '/' by default.
#
root = "/"
non_ssl_template = nil 
ssl_template     = nil 
apache2_dir      = nil

opts = GetoptLong.new(
         [ '--help', '-h', GetoptLong::NO_ARGUMENT ],
         [ '--verbose', '-v', GetoptLong::NO_ARGUMENT ],
         [ '--template', '-t', GetoptLong::REQUIRED_ARGUMENT ],
         [ '--force', '-f', GetoptLong::NO_ARGUMENT ]
       )

opts.each do |opt, arg|
  case opt
  when '--help'
    $HELP = true
  when '--verbose'
    $VERBOSE = true
  when '--template'
    ssl_template = arg
  when '--ssl-template'
    ssl_template = arg
  when '--non-ssl-template'
    non_ssl_template = arg
  when '--apache2-dir'
    apache2_dir = arg
  when '--root'
    root = arg
  when '--force'
    $FORCE = true
  end
end

#
# CAUTION! Here be quality kode.
#
if $HELP
  # Open the file, stripping the shebang line
  lines = File.open(__FILE__){|fh| fh.readlines}[2..-1]

  lines.each do |line|
    line.chomp!
    break if line.empty?
    puts line[2..-1].to_s
  end

  exit 0
end

def verbose(s)
  puts s if $VERBOSE
end

#
# Set the default paths.
#
non_ssl_template = File.join(root, "/etc/symbiosis/apache.d/non_ssl.template.erb") if non_ssl_template.nil?
ssl_template     = File.join(root, "/etc/symbiosis/apache.d/ssl.template.erb") if ssl_template.nil?
apache2_dir      = File.join(root, "/etc/apache2") if apache2_dir.nil?

#
# Any arguments on the command line specify which domains to do.
#
domains_to_configure = ARGV

primary_ips = [Symbiosis::Host.primary_ipv4, Symbiosis::Host.primary_ipv6]

#
#  For each domain.
#
Symbiosis::Domains.each do |domain|

  verbose "Domain: #{domain.name} "

  next unless domains_to_configure.empty? or domains_to_configure.include?(domain.name)

  begin
    sites_available_file = File.join(apache2_dir, "sites-available","#{domain.name}.conf")
    sites_enabled_file   = File.join(apache2_dir, "sites-available","#{domain.name}.conf")

    config        = Symbiosis::ConfigFiles::ApacheSSL.new(sites_available_file, "#")
    config.domain = domain

    if domain.ips.any?{|ip| primary_ips.include?(ip)}
      verbose "\tNot configuring this site, as it is using at least one of this host's primary IPs."
      next
    end

    #
    #  If SSL is not enabled then we can skip
    #
    if ( domain.ssl_enabled? )
      config.template = ssl_template

      verbose "\tSSL is enabled -- using SSL template"
    else
      config.template = non_ssl_template
    
      verbose "\tSSL is not enabled -- using non-SSL template"
    end

    #
    #  If there is already a site enabled we only
    # need to touch it if one of the SSL-files is more
    # recent than the generated file.
    #
    #  e.g. User adds /config/ssl.combined and a site
    # is generated but broken because a mandatory bundle is missing.
    #


    if ( $FORCE )
      verbose "\tForcing re-creation of configuration due to --force."

    elsif config.exists?

      if config.changed?
        verbose "\tNot updating configuration, as it has been edited by hand."
        next

      elsif config.outdated?
        verbose "\tRe-creating configuration as it is out of date."

      else
        verbose "\tSite already present and up-to date."
        next

      end

    else
      verbose "\tConfiguring site for the first time"

      end

    #
    # This gets apache2 to check the configuration using a temporary file.
    #
    if config.ok?

      verbose "\tWriting configuration"
      config.write
      
      # Definitely restart if we've rewritten the config.
      $RESTART = true

      unless config.enabled?(sites_enabled_file)
        verbose "\tEnabling site"
        config.enable(sites_enabled_file, $FORCE)
      end

    else
      verbose "\tApache has rejected the new configuration -- no changes have been made."
    end

    #
    # Rescue errors for this domain, but continue for others.
    #
  rescue StandardError => err
    warn "\tUnable to configure site for #{domain.name} because #{err.to_s}"
    verbose "\t"+err.backtrace.join("\n\t")
  end
end

#
#  All done.
#
if ( $RESTART )
  verbose "Restarting Apache"

  system( "/etc/init.d/apache2 restart" )
end
