#!/bin/sh
#
#  This script is designed to determine the name of any remote
# backup space associated with this machine and upload the local
# contents to it.
#
#  If there is a file "/etc/symbiosis/dns.d/backup.name" it
# is assumed to contain the name of the backup space to use, otherwise
# the name will be determined dynamically via a DNS lookup.
#
# Steve
# --
#



#
#  Local backup directory.
#
src=/var/backups/



#
#  The IP address associated with the interface eth0.
#
eth0=$(/sbin/ifconfig eth0 | grep 'inet addr:' | awk '{print $2}' | awk -F: '{print $2}' )


#
#  We need the IP reversed on an octet-basis for the DNS lookup..
#
one=$(echo $eth0   | awk -F\. '{print $1}')
two=$(echo $eth0   | awk -F\. '{print $2}')
three=$(echo $eth0 | awk -F\. '{print $3}')
four=$(echo $eth0  | awk -F\. '{print $4}')

#
#  Get the name via the DNS lookup
#
name=$(dig txt  $four.$three.$two.$one.backup-reverse.bytemark.co.uk +short | tr -d \")


#
#  The name might instead be hardwired.
#
#  If there is a hardwired result then we'll use that in preference
# to the name returned from the DNS lookup.
#
if [ -e /etc/symbiosis/dns.d/backup.name ]; then
    name=$(cat /etc/symbiosis/dns.d/backup.name)
fi



#
#  If we didn't get a name then exit.
#
if [ -z "$name" ]; then
    echo "Failed to determine backup space name for $eth0"
    exit 0
fi


#
#  OK we got a name of the form "foo.backup.bytemark.co.uk"
#
#  Truncate at the first part.
#
name=$(echo $name | awk -F\. '{print $1}' )

#
#  Now rsync.
#
#  If the name of the machine is example.vm.bytemark.co.uk we'll expect
# to upload to:
#
#    example.backup.bytemark.co.uk::example/example.vm.bytemark.co.uk/
#
rsync -vazr /var/backups $name.backup.bytemark.co.uk::$name/$(hostname --fqdn)/
