#!/bin/sh
#
# Overview
# --------
#
# This script is designed to determine the name of any remote
# backup space associated with this machine and upload the local
# archive, produced by backup2l, to this location.
#
# Override
# --------
#
# If there is a file "/etc/symbiosis/dns.d/backup.name" it
# is assumed to contain the name and path of a remote location to
# use for the rsync upload.
#
# Disabling
# ---------
#
# To disable uploads completely create the an empty file named
# "/etc/symbiosis/dns.d/backup.name".
#
# Steve
# --
#



#
#  Local backup directory.
#
src=/var/backups/



#
#  The remote rsync location might be hardwired.
#
#
if [ -e /etc/symbiosis/dns.d/backup.name ]; then

    #
    #  If the file is empty then we just abort.
    #
    if [ ! -s /etc/symbiosis/dns.d/backup.name ]; then
        exit 0;
    fi

    #
    #  Otherwise we can rsync immediately to the specified location
    #
    rsync -vazr /var/backups $(cat /etc/symbiosis/dns.d/backup.name)
    exit 0;
fi




###
##
#
#  OK we don't have an explicit name specified, so we need to look it up
# dynamically.
#
##
###



#
#  Find the IP address associated with eth0.
#
eth0=$(/sbin/ifconfig eth0 | grep 'inet addr:' | awk '{print $2}' | awk -F: '{print $2}' )



#
#  We need the IP reversed on an octet-basis for the DNS lookup.
#
one=$(echo $eth0   | awk -F\. '{print $1}')
two=$(echo $eth0   | awk -F\. '{print $2}')
three=$(echo $eth0 | awk -F\. '{print $3}')
four=$(echo $eth0  | awk -F\. '{print $4}')



#
#  Attempt to find the name of the associated backup space via a
# DNS lookup.
#
name=$(dig txt  $four.$three.$two.$one.backup-reverse.bytemark.co.uk +short | tr -d \")



#
#  If we didn't get a name then exit.
#
if [ -z "$name" ]; then
    echo "Failed to determine backup space name for $eth0"
    exit 0
fi


#
#  OK we got a name of the form "foo.backup.bytemark.co.uk"
#
#  Truncate at the first part.
#
name=$(echo $name | awk -F\. '{print $1}' )


#
#  Now rsync.
#
#  If the name of the machine is example.vm.bytemark.co.uk we'll expect
# to upload to:
#
#    example.backup.bytemark.co.uk::example/example.vm.bytemark.co.uk/
#
rsync -vazr /var/backups $name.backup.bytemark.co.uk::$name/$(hostname --fqdn)/

exit 0