#!/bin/bash

#
# This script has to use bash as it uses arrays.
#

set -e

#
# Skip, if we are not in "configure" state
#
if [ "$1" != "configure" ]; then
        echo "I: Skipping configuration"
        exit 0
fi


dpkg-divert --add --rename "/usr/sbin/symbiosis-httpd-logger" 

#DEBHELPER#
