#!/bin/sh

set -e

if [ "$1" = "upgrade" ] ; then
  #
  #  Do nothing for upgrades.
  #
  exit 0
fi

#
#  Reove the existing diversion
#
if dpkg-divert --list | grep -F "/usr/sbin/symbiosis-httpd-logger.distrib"
then
        dpkg-divert --remove --rename /usr/sbin/symbiosis-httpd-logger
fi
