#!/bin/bash
#
#  This script is designed to dump all the MySQL databases upon
# the local system.
#


#
#  If we don't have mysqld installed exit.
#
test -x /usr/sbin/mysqld      || exit 0
test -x /etc/init.d/mysql     || exit 0
test -e /etc/mysql/debian.cnf || exit 0


#
#  If we don't have a backup directory then create it.
#
if [ ! -d /var/backups/mysql ]; then
    mkdir -p /var/backups/mysql
fi


#
#  Get the username and password
#
user=$(grep user /etc/mysql/debian.cnf | awk '{print $3}' | head -n 1)
pass=$(grep pass /etc/mysql/debian.cnf | awk '{print $3}' | head -n 1)


#
#  For each database we find, dump it
#
for i in /var/lib/mysql/*/; do

    # the name of the database
    name=`basename $i`

    # do the dump
    mysqldump --opt --user="$user" --pass="$pass" $name | gzip > /var/backups/mysql/$name.gz

done

#
# Exit sanely.
#
exit 0
