#!/usr/bin/ruby 

require 'symbiosis/monitor/check'

class ClamdCheck < Symbiosis::Monitor::Check

  def initialize
    super
    @process.pidfile = "/var/run/clamav/clamd.pid"
    @process.initscript = "/etc/init.d/clamav-daemon"
    @name = "clamd"
  end

  def do_check
    return SystemExit::EX_CONFIG unless initscript_ok?

    r = do_process_check
    if SystemExit::EX_TEMPFAIL == r 
      should_be_running ? self.start : self.stop
    end
    return r
  end

  def should_be_running
    (0 < Dir.glob('/srv/*/config/antivirus').length)
  end
end

exit ClamdCheck.new.do_check if $0 == __FILE__

