#!/usr/bin/ruby

require 'symbiosis/monitor/check'

class FreshclamCheck < Symbiosis::Monitor::Check

  def initialize
    super
    @process.pidfile = "/var/run/clamav/freshclam.pid"
    @process.initscript = "/etc/init.d/clamav-freshclam"
    @name = "freshclam"
  end

  #
  # This is a monkey-patch for clamav under Jessie, which runs under systemd by
  # default, and doesn't write a pidfile.  Starting / stopping works via the
  # systemd/sysvinit compatibility layer.
  #
  def running
   `systemctl status clamav-freshclam.service`
	 if $? and $?.success?
      puts "Found clamav-freshclam running via systemctl"
      return true
    end

    super
  end

  def do_check
    #
    # Check the initscript.  If it is missing, make sure that the process is
    # actually suppose to be running, before raising an error.
    #
    unless initscript_ok?
      if should_be_running
        return SystemExit::EX_CONFIG
      else
        puts "Daemon state probably OK -- initscript is missing and #{@name} is not supposed to be running."
        return 0
      end
    end

    r = do_process_check
    if SystemExit::EX_TEMPFAIL == r
      should_be_running ? self.start : self.stop
    end
    return r
  end

  def should_be_running
    (0 < Dir.glob('/srv/*/config/antivirus').length)
  end
end

exit FreshclamCheck.new.do_check if $0 == __FILE__

