#!/usr/bin/ruby 

require 'symbiosis/monitor/check'

class SpamdCheck < Symbiosis::Monitor::Check

  def initialize
    super
    @process.pidfile = "/var/run/spamd.pid"
    @process.initscript = "/etc/init.d/spamassassin"
    @name = "spamd"
  end

  def should_be_running
    (0 < Dir.glob('/srv/*/config/antispam').length)
  end

  def do_check
    return SystemExit::EX_CONFIG unless initscript_ok?

    r = do_process_check 
    if SystemExit::EX_TEMPFAIL == r 
      should_be_running ? self.start : self.stop
    end

    return 0 unless should_be_running

    tcpconnection = Symbiosis::Monitor::TCPConnection.new( 
      "localhost", "spamd", ["PING SPAMC/1.3\r\n",nil]
    )
    r = do_tcpconnection_check(tcpconnection)
    self.restart if SystemExit::EX_TEMPFAIL == r 
    return r
  end

  def do_response_check(responses)
    raise "Unexpected response '#{responses.first}'" unless responses.first =~ /PONG/
  end

end

exit SpamdCheck.new.do_check if $0 == __FILE__

