#!/usr/bin/ruby
#

require 'symbiosis/utils'
require 'erb'
require 'symbiosis/domains'
require 'symbiosis/domain/mailbox'
require 'symbiosis/domain/emailpass_autoencrypt'

Symbiosis::Domains.each do |domain|
  #
  # Skip domains without email password auto encryption.
  #
  unless domain.has_emailautoenc?
    puts "#{domain.name} has not had email password auto encryption enabled.  Skipping."
    next
  end
  boxes =  domain.mailboxes
  boxes.each do |box|
    password_file = File.join(box.directory,"password")
    Symbiosis::Utils.safe_open(password_file,"a+") do |fn|
        contents = fn.read
        encrypted_pass =  domain.crypt_password(contents)
        Symbiosis::Utils.set_param("password", encrypted_pass, box.directory, :mode => 0600)
    end
  end
end
