#!/usr/bin/ruby
#

require 'symbiosis/utils'
require 'erb'
require 'symbiosis/domains'
require 'symbiosis/domain/mailbox'
require 'symbiosis/domain/emailpass_autoencrypt'

Symbiosis::Domains.each do |domain|
  #
  # Skip domains without email password auto encryption.
  #
  unless domain.has_emailautoenc?
    puts "#{domain.name} has not had email password auto encryption enabled.  Skipping." if $VERBOSE
    next
  end

  domain.mailboxes.each do |box|
    #
    #
    # Maybe more logging here to show passwords that are being changed?
    #
    box.password = box.password
  end
end
