#!/usr/bin/ruby
#
# NAME
#
#  symbiosis-email-encrypt-passwords - Automatic hashing for user passwords
#  
#  passwords already encrypted will remain unaltered
#
# SYNOPSIS
#
#  symbiosis-email-encrypt-passwords [ -h | --help ] [-m | --manual]
#
# OPTIONS
#
#  -h, --help            Show a help message, and exit.
#
#  -m, --manual          Show this manual, and exit.
#
#
# AUTHOR
#
# Patrick J. Cherry <patrick@bytemark.co.uk>
#

require 'getoptlong'

manual = help = false
opts = GetoptLong.new(
         [ '--help',       '-h', GetoptLong::NO_ARGUMENT ],
         [ '--manual',     '-m', GetoptLong::NO_ARGUMENT ]
       )

opts.each do |opt,arg|
  case opt
  when '--help'
    help = true
  when '--manual'
    manual = true
  end
end

#
# Output help as required.
#
if help or manual
  require 'symbiosis/utils'
  Symbiosis::Utils.show_help(__FILE__) if help
  Symbiosis::Utils.show_manual(__FILE__) if manual
  exit 0
end

#
# Require these bits here, so we can generate the manpage without needing extra
# build-deps.
#

require 'symbiosis/utils'
require 'symbiosis/domains'
require 'symbiosis/domain/mailbox'
require 'symbiosis/domain/emailpass_autoencrypt'

Symbiosis::Domains.each do |domain|
  #
  # Skip domains without email password auto encryption.
  #
  unless domain.should_encrypt_mailbox_passwords?
    puts "#{domain.name} has not had email password auto encryption enabled.  Skipping." if $VERBOSE
    next
  end

  domain.mailboxes.each do |box|
    #
    #
    # Maybe more logging here to show passwords that are being changed?
    #
    box.password = box.password
  end
end
