#!/bin/sh

set -e

#
# Skip, if we are not in "configure" state
#
if [ "$1" != "configure" ]; then
    echo "I: Skipping configuration"
    exit 0
fi

#
#  Add the keys
#
for i in /usr/share/symbiosis-key/*.pub; do
  apt-key add $i
done


#DEBHELPER#
exit 0
