#!/bin/bash

set -e

#
# Skip, if we are not in "configure" state
#
if [ "$1" != "configure" ]; then
    echo "I: Skipping configuration"
    exit 0
fi

#
#  Add the keys
#
for i in /usr/share/symbiosis/key/*.pub; do
  apt-key add $i > /dev/null 2>&1
done

#
# Remove any old keys
#
for i in 9703BD62 F3562818 6734A3BF 23E96D7D ; do
  apt-key del $i > /dev/null 2>&1 || echo "I: Old Symbiosis key ID $i not found"
done

#DEBHELPER#
exit 0
