#!/bin/sh -eu

if ! [ "$1" = "live-update" ] ; then
  echo "I: $0: Ignoring unknown hook action $1"
  exit 0
fi

#
# Only dovecot needs reloading following a certificate change
#
exec service dovecot reload

