#!/bin/bash
#

set -e

PREFIX=$(dirname ${0})
ACTION="install"

dpkg --clear-avail

if [ -f $PREFIX/conf/action ] ; then
  ACTION=$(< ${PREFIX}/conf/action)
fi

# echo "Acquire::http::Proxy::maker2.bytemark.co.uk DIRECT;" > /etc/apt/apt.conf.d/95proxy
# echo "Acquire::http::Proxy \"http://maker2.bytemark.co.uk:3142\";" >> /etc/apt/apt.conf.d/95proxy

if [ "upgrade" = "$ACTION" ] ; then
  echo "I: Installing current version of Symbiosis from repo.bytemark.co.uk"
  $PREFIX/bin/apt-get-install $PREFIX/conf/current-jessie-sources.list $PREFIX/conf/jessie-packages
    
  echo "I: Re-seed debconf"
  $PREFIX/02-seed-debconf

  echo "I: Performing dist-upgrade"
  $PREFIX/bin/apt-get-install $PREFIX/conf/maker-sources.list

elif [ "dist-upgrade" = "$ACTION" ] ; then
  #
  # If we're upgrading from squeeze:
  #
  if grep -q wheezy /etc/apt/sources.list ; then
    echo "I: Installing wheezy version of Symbiosis from repo.bytemark.co.uk"
    $PREFIX/bin/apt-get-install $PREFIX/conf/current-wheezy-sources.list $PREFIX/conf/wheezy-packages || true

    echo "I: Replacing wheezy sources with jessie"
    cp $PREFIX/conf/debian-jessie-sources.list /etc/apt/sources.list

    echo "I: Removing old wheezy symbiosis list"
    rm /etc/apt/sources.list.d/current-wheezy-sources.list

    #echo "I: clamav with squeeze is a bit ropey, so I'll clear out the freshclam stuff"
    #invoke-rc.d clamav-daemon stop
    #invoke-rc.d clamav-freshclam stop
    #rm $VERBOSE -f /var/lib/clamav/*.cv?

    echo "I: make sure services are running"
    $PREFIX/11-monit

    echo "I: Re-seed debconf"
    $PREFIX/02-seed-debconf
  fi

  #
  # Now upgrade to jessie
  #
  echo "I: Performing dist-upgrade from wheezy"

  #
  # If the install has failed, try to start pure-authd and carry on
  #
  if ! $PREFIX/bin/apt-get-install $PREFIX/conf/maker-sources.list ; then
    service pure-authd start
    $PREFIX/bin/apt-get-install $PREFIX/conf/maker-sources.list 
  fi

  echo "I: Re-seed debconf"
  $PREFIX/02-seed-debconf

  echo "I: ensuring Symbiosis packages are installed"
  $PREFIX/bin/apt-get-install $PREFIX/conf/maker-sources.list $PREFIX/conf/jessie-packages
else 


  echo "I: Installing latest version of Symbiosis from maker2.bytemark.co.uk"
  $PREFIX/bin/apt-get-install $PREFIX/conf/maker-sources.list $PREFIX/conf/jessie-packages
fi

