#!/bin/bash

set -e

#
# Skip, if we are not in "configure" state
#
if [ "$1" != "configure" ]; then
    echo "I: Skipping configuration"
    exit 0
fi

#
#  If there is volatile then comment it out.
#
if ( grep -q volatile /etc/apt/sources.list 2>/dev/null >/dev/null ); then
  sed -i -e 's/^[^#].*volatile.*$/# Removed since volatile no longer exists for squeeze\n# \0/g' /etc/apt/sources.list
fi

######################################
#
# Divert config files.  This is cribbed from config-package-dev.
#
######################################

mangle_config() {
  package=bytemark-symbiosis
  file="$1"
  ourfile="$file.dpkg-symbiosis"
  theirfile="$file.dpkg-symbiosis-orig"

  #
  # Add the diversion, if it doesn't exist.
  #
  if ! dpkg-divert --list "$package" | \
    grep -xFq "diversion of $file to $theirfile by $package"; then
    dpkg-divert --divert "$theirfile" --rename --package "$package" --add "$file"

  fi

  #
  # Now add the link in, unless it is already in place.
  #
  if [ ! -L "$file" ] && [ ! -e "$file" ]; then

    ln -s "$(basename "$ourfile")" "$file"

  elif [ ! -L "$file" ] || \
       [ "$(readlink "$file")" != "$(basename "$ourfile")" -a \
         "$(readlink "$file")" != "$(basename "$theirfile")" ]; then

    echo "E: $file is not linked to either $(basename "$ourfile") or $(basename "$theirfile")" >&2

  fi
}

#
# Add in diversions
#
if [ "$1" = configure ] ; then
  mangle_config /etc/update-motd.d/00-header
  mangle_config /etc/update-motd.d/10-help-text
  mangle_config /etc/update-motd.d/90-updates-available.dpkg-symbiosis
  mangle_config /etc/update-motd.d/98-fsck-at-reboot.dpkg-symbiosis
fi

#DEBHELPER#
exit 0
