#!/bin/sh

set -e

#
# Ugh.. this is copied from the preinst.
#

function do_upgrade() {

  ##### Config adjustments ################
  #
  # Array of config files to remove
  #
  declare -a files_to_remove

  files_to_remove+=("/etc/dovecot/symbiosis.d/30-authentication/50-passdb-checkpassword"
    "/etc/dovecot/symbiosis.d/30-authentication/85-userdb-checkpassword"
  )

  for file in ${files_to_remove[*]} ; do
   dpkg-maintscript-helper rm_conffile \
     $file \
     "2014:1231" symbiosis-email -- "$@"
  done

  unset files_to_remove
}

#
# Skip, if we are not in "configure" state
#
if [ "$1" != "configure" ]; then
        echo "I: Skipping configuration"
        exit 0
fi

do_upgrade $@

if ! ( groups clamav | grep -q Debian-exim ) ; then
  #
  #  Add the user
  #
  adduser clamav Debian-exim
fi

#
# Set the TMPDIR variable for clamav.
#
echo "TMPDIR='/var/tmp/'" >> /etc/default/clamav-daemon

#
#  Enable the spamassassin module
#
if [ -e /etc/default/spamassassin ]; then
    sed -i -e 's/^\(ENABLED=\)0/\11/' /etc/default/spamassassin
fi

#
# Enable spamassassin daily updates
#
if [ -e /etc/default/spamassassin ]; then
    sed -i -e 's/^\(CRON=\)0/\11/' /etc/default/spamassassin
fi

#
#  Make sure ownership is correct on our file
#
touch /etc/exim4/rewrites
chown Debian-exim /etc/exim4/rewrites

#
#  Rebuild exim4
#
if [ -e /etc/exim4/Makefile ]; then
    cd /etc/exim4 && make
fi

#
#  Rebuild dovecot
#
if [ -e /etc/dovecot/Makefile ] ; then
    cd /etc/dovecot && make
fi

#
#  Restart all deamons
#
for i in spamassassin clamav-daemon exim4 dovecot symbiosis-email-dict-proxy; do
    # spamassassin + clamav-daemon might not be installed.  Wrap the invokation.
    service $i restart || true
done

#DEBHELPER#
exit 0
