#!/bin/sh

set -e

if [ "$1" = "purge" ] ; then
  if [ -e /etc/exim4/exim4.conf ] ; then
    echo "I: Removing exim4.conf"
    rm /etc/exim4/exim4.conf
  fi

  if [ -e /etc/dovecot/dovecot.conf.dpkg-symbiosis ] ; then
    echo "I: Removing dovecot.conf.dpkg-symbiosis"
    rm /etc/dovecot/dovecot.conf.dpkg-symbiosis
  fi 

  #
  # Configure supplementary groups for clamav and freshclam
  #
  if ( groups clamav | grep -q Debian-exim ) ; then
    echo "I: Removing Debian-exim group to clamav"
    deluser clamav Debian-exim
  fi
  
  . /usr/share/debconf/confmodule
  if ( db_get clamav-daemon/AddGroups | grep -q Debian-exim ) ; then
    db_set clamav-daemon/AddGroups ''
  fi

  if ( grep -q '^AllowSupplementaryGroups \+true' /etc/clamav/clamd.conf ) ; then
    echo "I: Disallowing clamav to operate using its supplementary groups"
    sed -i -e 's/^AllowSupplementaryGroups .*$/AllowSupplementaryGroups false/' /etc/clamav/clamd.conf
  fi
fi

#
#  Restart all deamons
#
for i in spamassassin clamav-daemon exim4 dovecot ; do
    # spamassassin + clamav-daemon might not be installed.  Wrap the invokation.
    service $i restart || true
done

#DEBHELPER#

exit 0
