#!/bin/bash

#
# This script has to use bash as it uses arrays.
#

set -e

#
# Ugh.. this is copied from the preinst.
#

function do_upgrade() {

  ##### Config adjustments ################
  #
  # Array of config files to remove
  #
  declare -a files_to_remove

  files_to_remove+=("/etc/dovecot/symbiosis.d/30-authentication/50-passdb-checkpassword"
    "/etc/dovecot/symbiosis.d/30-authentication/85-userdb-checkpasswd"
  )

  for file in ${files_to_remove[*]} ; do
   dpkg-maintscript-helper rm_conffile \
     $file \
     "2014:1231" symbiosis-email -- "$@"
  done

  unset files_to_remove
}

#
# Skip, if we are not in "configure" state
#
if [ "$1" != "configure" ]; then
        echo "I: Skipping configuration"
        exit 0
fi

do_upgrade $@

#
# Configure supplementary groups for clamav and freshclam
#
if ! ( groups clamav | grep -q Debian-exim ) ; then
  #
  #  Add the user
  #
  echo "I: Adding Debian-exim group to clamav"
  adduser clamav Debian-exim
fi

. /usr/share/debconf/confmodule
if ! ( db_get clamav-daemon/AddGroups | grep -q Debian-exim ) ; then
  db_set clamav-daemon/AddGroups 'Debian-exim'
fi

if ( grep -q '^AllowSupplementaryGroups \+false' /etc/clamav/clamd.conf ) ; then
  echo "I: Allowing clamav to operate using its supplementary groups"
  sed -i -e 's/^AllowSupplementaryGroups .*$/AllowSupplementaryGroups true/' /etc/clamav/clamd.conf
fi 

#
# Set the TMPDIR variable for clamav.
#
echo "TMPDIR='/var/tmp/'" >> /etc/default/clamav-daemon

#
#  Enable the spamassassin module
#
if [ -e /etc/default/spamassassin ]; then
    sed -i -e 's/^\(ENABLED=\)0/\11/' /etc/default/spamassassin
fi

#
# Enable spamassassin daily updates
#
if [ -e /etc/default/spamassassin ]; then
    sed -i -e 's/^\(CRON=\)0/\11/' /etc/default/spamassassin
fi

#
#  Make sure ownership is correct on our file
#
touch /etc/exim4/rewrites
chown Debian-exim /etc/exim4/rewrites

#
#  Rebuild exim4
#
if [ -e /etc/exim4/Makefile ]; then
    cd /etc/exim4 && make
fi

# 
# Dovecot ships with its own config.
#
package="symbiosis-email"
conf="/etc/dovecot/dovecot.conf"
theirfile="$conf.dpkg-symbiosis-orig"

#
# Add the diversion, if it doesn't exist.
#
if ! dpkg-divert --list "$package" | \
  grep -xFq "diversion of $conf to $theirfile by $package"; then

  dpkg-divert --divert "$theirfile" --rename --package "$package" --add "$conf"
fi

#
#  Rebuild dovecot
#
if [ -e /etc/dovecot/Makefile ] ; then
    cd /etc/dovecot && make
fi

#
#  Restart all deamons
#
for i in spamassassin clamav-daemon symbiosis-email-dict-proxy; do
    # spamassassin + clamav-daemon might not be installed.  Wrap the invokation.
    service $i restart || true
done

#DEBHELPER#
exit 0
