#!/bin/bash

set -e

#
# This makes sure old config files are removed without dpkg prompts
#
for file in 50-rewrite/10-localhost-rewrite ; do
 dpkg-maintscript-helper rm_conffile \
   /etc/exim4/symbiosis.d/$file \
   "2013:0731" -- "$@"
done


#
# Move the exim4 config out of the way when upgrading (it will be regenerated later)
#
if [ -e /etc/exim4/exim4.conf ] ; then
  echo "I: Moving exim4.conf out of the way to prevent breakage on upgrade"
  mv -vf /etc/exim4/exim4.conf /etc/exim4/exim4.conf.symbiosis-old
fi

#DEBHELPER#
exit 0

