#!/bin/bash

#
# This script has to use bash as it uses arrays.
#

set -e

function do_upgrade() {

  ##### Config adjustments ################ 
  #
  # Array of config files to remove
  #
  declare -a files_to_remove

  files_to_remove+=("/etc/dovecot/symbiosis.d/30-authentication/50-passdb-checkpassword"
    "/etc/dovecot/symbiosis.d/30-authentication/85-userdb-checkpasswd"
  )

  for file in ${files_to_remove[*]} ; do
   dpkg-maintscript-helper rm_conffile \
     $file \
     "2014:1231" symbiosis-email -- "$@"
  done
}

case "$1" in
    install)
      # do nothing
    ;;

    upgrade)
      do_upgrade $@
    ;;

    abort-upgrade)
    ;;

    *)
        echo "preinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#
exit 0
