#!/bin/bash

set -e

if [ "$1" == "upgrade" ] ; then
  if echo $2 | grep -q ^2014: && [ -f /etc/exim4/exim4.conf ] ; then
    # upgrading to wheezy - get rid of gnutls config that breaks the upgrade
    sed -i /etc/exim4/exim4.conf \
      -e 's/^tls_require_ciphers/#tls_require_ciphers/g'
  fi
  exit 0
fi

#
# Remove the clamav defaults file, if it matches the md5sum of the one we created.
#
if echo "ae779d6822f91492b26697d6b9931835  /etc/default/clamav-daemon" | md5sum -c --status 2>/dev/null ; then
  rm -f /etc/default/clamav-daemon
fi

exit 0

