#!/bin/bash

#
# This script has to use bash as it uses arrays.
#

set -e

#
# Skip, if we are not in "configure" state
#
if [ "$1" != "configure" ]; then
        echo "I: Skipping configuration"
        exit 0
fi

#
# Restart apache2 for our dpush snippet
#
if [ -e /usr/share/apache2/apache2-maintscript-helper ] ; then
    . /usr/share/apache2/apache2-maintscript-helper
    apache2_invoke enconf symbiosis-email-activesync.conf || true
fi

#DEBHELPER#
exit 0
