#!/bin/bash

set -e

#
# Skip, if we are not in "configure" state
#
if [ "$1" != "configure" ]; then
        echo "I: Skipping configuration"
        exit 0
fi

#
# Remove old config files
#
rm -f /etc/apache2/conf.d/squirrelmail.local.conf

#
#  Restart Apache2.
#
if which invoke-rc.d >/dev/null 2>&1; then
    invoke-rc.d apache2 force-reload || true
else
    /etc/init.d/apache2 force-reload || true
fi

#DEBHELPER#
exit 0
