#!/bin/bash

set -e

#
# Skip, if we are not in "configure" state
#
if [ "$1" != "configure" ]; then
        echo "I: Skipping configuration"
        exit 0
fi

#
# Remove old config files
#
rm -f /etc/apache2/conf.d/squirrelmail.local.conf

#
# Restart apache to pick up webmail/ link
#
invoke-rc.d apache2 reload || true

#DEBHELPER#
exit 0
