#!/bin/bash

set -e

#
# Skip, if we are not in "configure" state
#
if [ "$1" != "configure" ]; then
        echo "I: Skipping configuration"
        exit 0
fi

#
# Update our webmail alternative.
#
update-alternatives --install /var/www/webmail symbiosis-webmail /var/lib/roundcube/ 100

#
# Restart apache2 if the apache2ctl exists and is exectuable
#
if [ -x /usr/sbin/apache2ctl ] ; then

  #
  #  Restart Apache2.
  #
  invoke-rc.d apache2 force-reload || true

fi

#DEBHELPER#
exit 0
