#!/bin/bash
#
#  This script has the task of performing the "common" post-install
# setup for all the Symbiosis packages.
#
#  It shouldn't do anything too package-specific, as that is a task
# for the specific packages, but global actions are good.
#
#
# Steve
# --
#




#
# Skip, if we are not in "configure" state
#
if [ "$1" != "configure" ]; then
        echo "I: Skipping configuration"
        exit 0
fi



#
#  Shadow passwords must be on.
#
/sbin/shadowconfig on 2>/dev/null >/dev/null



#
#  If there isn't an admin account add it.
#
if ( ! grep ^admin: /etc/passwd 2>/dev/null >/dev/null ); then

    echo "Adding 'admin' account"
    useradd  --home=/srv admin --shell=/bin/bash

    #
    #  Now set the password for admin to that used by root if it isn't there
    #
    usermod -p $(grep root /etc/shadow | awk -F: '{print $2}') admin
fi


#
#  Add group if missing
#
if ( ! grep ^admin: /etc/group 2>/dev/null >/dev/null ); then
    addgroup admin
fi

#
#  If we have an adm group - which we shold - add the admin user to it.
#
if ( grep ^adm: /etc/group 2>/dev/null >/dev/null ); then
    adduser admin adm  >/dev/null 2>/dev/null || true
fi

#
#  If we don't have the sudoers file setup then configure it
#
if [ -e /etc/sudoers ]; then

    #
    #  Not already present?
    #
    if ( ! grep ^admin /etc/sudoers 2>/dev/null >/dev/null ); then

        #
        #  Add it.
        #
        echo 'admin ALL = (ALL) ALL' >> /etc/sudoers
    fi
fi


#
# Make sure /etc/symbiosis exists
#
[ -d /etc/symbiosis ] || mkdir -p /etc/symbiosis

#
#  If we have a plaintext password stored in a previous location then
# we should move it to the new location.
#
passwd=""
for i in /etc/bytemark-vhost/.vhost.pass /etc/.vhost.pass ; do
    if [ -e $i ]; then
        if [ -s $i ]; then
            mkdir -p /etc/symbiosis || true
            cat $i > /etc/symbiosis/.passwd
        fi
        rm -f $i
    fi
done

#
#  If we have a stored password, in plaintext no less, ensure that
# it isn't visible to the world.
#
if [ -e /etc/symbiosis/.passwd ]; then
    chown root:root /etc/symbiosis/.passwd
    chmod 0600      /etc/symbiosis/.passwd
fi


#
#
#  If there are no existing directories beneath /srv/ create a default.
#
if [ $(ls -l /srv/ | grep ^d | wc -l) -lt 1 ] ; then

    #
    #  Roots
    #
    mkdir -p /srv/$(hostname --fqdn)/public/htdocs
    mkdir -p /srv/$(hostname --fqdn)/public/cgi-bin
    mkdir -p /srv/$(hostname --fqdn)/mailboxes/root


    #
    #  If we have a password then set it for the mailbox.
    #
    if [ -s /etc/symbiosis/.passwd ]; then
        cat /etc/symbiosis/.passwd  > /srv/$(hostname --fqdn)/mailboxes/root/password
    fi

    chown -R admin:admin /srv/
fi


#
#  Fix all perms
#
for i in /srv /srv/* ; do
    if [ -e $i ]; then
        if [ -d $i ] ; then
            owner=`stat --format='%U.%G' $i`
            if [ "$owner" = "root.root" ]; then
                chown -R admin:admin $i
            fi
        fi
    fi
done


#DEBHELPER#
exit 0
