#!/bin/sh
#
#  This script has the task of performing the "common" post-install
# setup for all the Symbiosis packages.
#
#  It shouldn't do anything too package-specific, as that is a task
# for the specific packages, but global actions are good.
#
#
# Steve
# --
#



set -e



#
# Skip, if we are not in "configure" state
#
if [ "$1" != "configure" ]; then
        echo "I: Skipping configuration"
        exit 0
fi



#
#  Shadow passwords must be on.
#
/sbin/shadowconfig on 2>/dev/null >/dev/null



#
#  If there isn't an admin account add it.
#
if ( ! grep ^admin: /etc/passwd 2>/dev/null >/dev/null ); then

    echo "Adding 'admin' account"
    useradd  --home=/srv admin --shell=/bin/bash

    #
    #  Now set the password for admin to that used by root if it isn't there
    #
    usermod -p $(grep root /etc/shadow | awk -F: '{print $2}') admin
fi


#
#  Add group if missing
#
if ( ! grep ^admin: /etc/group 2>/dev/null >/dev/null ); then
    addgroup admin
fi


#
#  If we don't have the sudoers file setup then configure it
#
if [ -e /etc/sudoers ]; then

    #
    #  Not already present?
    #
    if ( ! grep ^admin /etc/sudoers 2>/dev/null >/dev/null ); then

        #
        #  Add it.
        #
        echo 'admin ALL = (ALL) ALL' >> /etc/sudoers
    fi
fi


#
#  If there are no existing directories beneath /srv/ create a default.
#
if [ $(ls -l /srv/ | grep ^d | wc -l) -lt 1 ] ; then

    #
    #  Roots
    #
    mkdir -p /srv/$(hostname --fqdn)/public/htdocs
    mkdir -p /srv/$(hostname --fqdn)/public/cgi-bin
    mkdir -p /srv/$(hostname --fqdn)/mailboxes/root

    #
    #  Copy the password if present
    #
    for i in /etc/bytemark-vhost/ /etc/ ; do
        if [ -e $i/.vhost.pass ]; then
            cat $i/.vhost.pass > /srv/$(hostname --fqdn)/mailboxes/root/password

            #
            #  This is a migration to make sure we store the
            # password somewhere safe
            #
            if [ ! -d /etc/symbiosis ]; then
                mkdir -p /etc/symbiosis
            fi
            cat $i/.vhost.pass > /etc/symbiosis/.passwd

        fi
    done

    chown -R admin:admin /srv/
fi

#DEBHELPER#
exit 0
