#!/bin/bash
#

set -e

#
# Skip, if we are not in "configure" state
#
if [ "$1" != "configure" ]; then
        echo "I: Skipping configuration"
        exit 0
fi

#
# Double check this file gets installed with the correct permissions
#
if ( ! dpkg-statoverride --list /etc/sudoers.d/symbiosis > /dev/null ) ; then
  dpkg-statoverride --add --update root root 0440 /etc/sudoers.d/symbiosis
fi

#
# Shadow passwords must be on.
#
shadowconfig on

#
#  If there isn't an admin account add it.
#
if ( ! grep ^admin: /etc/passwd 2>/dev/null >/dev/null ); then

  echo "Adding 'admin' account"
  adduser --home=/srv --shell=/bin/bash --no-create-home --disabled-login --gecos='Symbiosis Administrator,,,' admin

  #
  #  Now set the password for admin to that used by root if it isn't there
  #
  usermod -p "$(grep root /etc/shadow | cut -f 2 -d :)" admin

  #
  #  If we have an adm group - which we shold - add the admin user to it.
  #
  if ( getent group adm >/dev/null ); then
    adduser admin adm
  fi
fi

#
# Add a stat override for the /srv directory.
#
if ( ! dpkg-statoverride --list /srv > /dev/null ) ; then
  dpkg-statoverride --add --update admin admin 2755 /srv
fi

#
# Find the hostname, if not set already.
#
if [ -z "$HOSTNAME" ] ; then
  if [ -f /etc/hostname ] ; then
    HOSTNAME=$(< /etc/hostname)
  else
    HOSTNAME=$(hostname --fqdn)
  fi
fi

#
#  If there are no existing directories beneath /srv/ create a default.
#
if [ -n "$HOSTNAME" -a "$(find /srv -maxdepth 1 -mindepth 1 -type d | wc -l)" = "0" ] ; then
  #
  # Create the standard directories
  #
  mkdir -p /srv/$HOSTNAME/public/htdocs
  mkdir -p /srv/$HOSTNAME/config
  mkdir -p /srv/$HOSTNAME/mailboxes/root

  chown -R admin:admin /srv/$HOSTNAME
fi

if [ -e /etc/ssl/ssl.crt ] && [ -e /etc/ssl/ssl.key ] ; then
  #
  # Make sure the certificate is at least as recent as the key, to avoid
  # overwriting it.
  #
  touch -r /etc/ssl/ssl.key /etc/ssl/ssl.crt
fi

#
# Generate SSL certificates.
#
cd /etc/ssl && make check || true

#DEBHELPER#

exit 0
