#!/bin/bash
#
#  This script has the task of performing the "common" post-install
# setup for all the Symbiosis packages.
#
#  It shouldn't do anything too package-specific, as that is a task
# for the specific packages, but global actions are good.
#
#
# Steve
# --
#

set -e

#
# Remove the statoverride
#
/usr/sbin/dpkg-statoverride --remove /etc/sudoers.d/symbiosis

#DEBHELPER#
exit 0
