#!/bin/bash

set -e

# Prepare to move a conffile without triggering a dpkg question
prep_mv_conffile() {
    local PKGNAME="$1"
    local CONFFILE="$2"

    [ -e "$CONFFILE" ] || return 0

    local md5sum="$(md5sum $CONFFILE | sed -e 's/ .*//')"
    local old_md5sum="$(dpkg-query -W -f='${Conffiles}' $PKGNAME | \
            sed -n -e "\' $CONFFILE ' { s/ obsolete$//; s/.* //; p }")"
    if [ "$md5sum" = "$old_md5sum" ]; then
        rm -f "$CONFFILE"
    fi
}

case "$1" in
install|upgrade)
  if dpkg --compare-versions "$2" le "$LASTVERSION"; then
    for pkg in bytemark-vhost-tinydns symbiosis-tinydns ; do   
      for fn in `dpkg-query -W -f='${Conffiles}' $pkg | grep '/etc/exim4/bytemark-vhost.d' |  cut -f 2 -d ' '` ; do
        prep_mv_conffile $pkg $fn
      done
    done
  fi
esac

#DEBHELPER#
exit 0

