#!/bin/bash

#
# This script has to use bash as it uses arrays.
#

set -e

function do_upgrade() {

  ##### Config adjustments ################ 
  #
  # Array of config files to remove
  #
  declare -a files_to_remove

  files_to_remove+=(
    "/etc/exim4/symbiosis.d/00-main/21-bytemark-antispam-hostlist"
    "/etc/exim4/symbiosis.d/10-acl/50-acl-check-rcpt/70-bytemark-antispam-defer"
  )

  for file in ${files_to_remove[*]} ; do
   dpkg-maintscript-helper rm_conffile \
     $file \
     "2014:1231" symbiosis-dns -- "$@"
  done
}

case "$1" in
    install)
      # do nothing
    ;;

    upgrade)
      do_upgrade $@
    ;;

    abort-upgrade)
    ;;

    *)
        echo "preinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#
exit 0
