#!/bin/sh

set -e

#
# Skip, if we are not in "configure" state
#
if [ "$1" != "configure" ]; then
        echo "I: Skipping configuration"
        exit 0
fi

#DEBHELPER#

#
# Add symlinks for the monit script
# 
monit_dir="/etc/symbiosis/monit.d"
mkdir -p "$monit_dir"

for i in mysqld; do
  monit_script="/usr/share/symbiosis/monit/checks/$i"
  link_target="$monit_dir/$i"

  if [ -x "$monit_script" ] && [ ! -e "$link_target" ]; then
    echo "I: Adding symlink for Symbiosis Monit script for $i"
    ln -s "$monit_script" "$link_target" || true
  fi
done

#
# Restart mysql just in case the config has been modified.
#
invoke-rc.d mysql restart

exit 0
