#!/bin/bash

set -e

#
# Skip, if we are not in "configure" state
#
if [ "$1" != "configure" ]; then
    echo "I: Skipping configuration"
    exit 0
fi

#
#  Remove the old files we might have had present by accident
#
for i in /etc/cron.d/bytemark-vhost-updater /etc/cron.d/symbiosis-update /etc/cron.daily/cron-apt /etc/cron.daily/update-packages /etc/update-packages.conf /etc/symbiosis/updater  ; do
    if [ -e $i ]; then
        rm -f $i || true
    fi
done


#DEBHELPER#
exit 0
