#!/bin/bash

set -e

#
# Skip, if we are not in "configure" state
#
if [ "$1" != "configure" ]; then
    echo "I: Skipping configuration"
    exit 0
fi

#
#  Make sure we notify the local sysadmin
#
if [ ! -e /etc/symbiosis/updater ]; then
    echo "EMAIL=root" >/etc/symbiosis/updater
fi

#
#  remove old config file
#
if [ -e /etc/update-packages.conf ]; then
    rm /etc/update-packages.conf
fi

#
#  Remove old configuration file.
#
if [ -e /etc/cron.daily/cron-apt ]; then
    rm /etc/cron.daily/cron-apt
fi

#
#  Remove the old files we might have had present by accident
#
for i in /etc/cron.daily/update-packages /etc/cron.d/bytemark-vhost-updater /etc/cron.d/symbiosis-update ; do
    if [ -e $i ]; then
        rm -f $i ;
    fi
done

#
# Make sure squeeze-lts features in /etc/apt/sources.list (this is for the updater to work)
#
if ! grep -q squeeze-lts /etc/apt/sources.list ; then
  cat >> /etc/apt/sources.list <<EOF

#
# Debian 6.0 (Squeeze) LTS -- https://www.debian.org/News/2014/20140424
#
deb     http://mirror.bytemark.co.uk/debian/     squeeze-lts main contrib non-free
deb-src http://mirror.bytemark.co.uk/debian/     squeeze-lts main contrib non-free

EOF
fi

#DEBHELPER#
exit 0
