#!/bin/sh

set -e

#
# Skip, if we are not in "configure" state
#
if [ "$1" != "configure" ]; then
    echo "I: Skipping configuration"
    exit 0
fi

#
# Remove the old duff cronjob if it exists
#
if [ -e /etc/cron.d/bytemark-service-monitor ] ; then
  rm -f /etc/cron.d/bytemark-service-monitor
fi

#
#  Cronjob needs to be removed on upgrade.
#
if [ -e /etc/cron.d/bytemark-vhost-monit ]; then
  rm -f  /etc/cron.d/bytemark-vhost-monit
fi

#
#  Remove old packaging mistake, if it still exists.
#
if [ -e /etc/bytemark-vhost/cron.d/bytemark-service-monitor ]; then
  rm -f /etc/bytemark-vhost/cron.d/bytemark-service-monitor
fi

if [ -d /etc/bytemark-vhost/cron.d ]; then
    rm -rf /etc/bytemark-vhost/cron.d
fi

if [ -d /etc/bytemark-vhost/monit.d ]; then
    rm -rf /etc/bytemark-vhost/monit.d
fi


#DEBHELPER#
exit 0
