#!/bin/bash

set -e

#
# Skip, if we are not in "configure" state
#
if [ "$1" != "configure" ]; then
  exit 0
fi

#
#  The prefix of our tree.
#
PREFIX=/etc/symbiosis/firewall

chown -R admin:admin $PREFIX

#DEBHELPER#

exit 0
