#!/bin/bash

set -e

for i in {client,server} ; do
  fn="/etc/symbiosis/firewall/incoming.d/50-xmpp-$i"
  if [ -f "$fn" ] && [ -z "$(<$fn)" ] ; then
    echo "I: Removing XMPP $i firewall rule..."
    rm "$fn"
  fi
done

#
# Restart all deamons
#
invoke-rc.d $i prosody || true

#DEBHELPER#
exit 0
