#!/bin/bash

set -e

#
# Add firewall rules
#
for i in {client,server} ; do
  fn="/etc/symbiosis/firewall/incoming.d/50-xmpp-$i"
  if [ -d $(dirname $fn) ] ; then
    echo "I: Adding XMPP $i firewall rule..."
    touch "$fn"
    chown admin:admin "$fn"
  fi
done


if [ ! -f /var/spool/prosody/dhparams ] ; then
  #
  # Generate dhperams if they don't exist already
  #
  /etc/cron.weekly/symbiosis-xmpp --verbose
fi

#
# Configure sites
#
symbiosis-xmpp-configure --verbose

#
# Restart prosody
#
invoke-rc.d prosody restart || true

#DEBHELPER#
exit 0
