#!/bin/bash

set -e

#
# Add firewall rules
#
for i in {client,server} ; do
  fn="/etc/symbiosis/firewall/incoming.d/50-xmpp-$i"
  if [ -d $(dirname $fn) ] ; then
    echo "I: Adding XMPP $i firewall rule..."
    touch "$fn"
    chown admin:admin "$fn"
  fi
done


if [ ! -f /var/spool/prosody/dhparams ] ; then
  #
  # Generate dhperams if they don't exist already
  #
  /etc/cron.weekly/symbiosis-xmpp --verbose
fi

#
# Configure sites
#
symbiosis-xmpp-configure --verbose

#
#  Rebuild dovecot
#
if [ -e /etc/dovecot/Makefile ] ; then
    cd /etc/dovecot && make
fi

#
#  Restart all daemons
#
for i in prosody dovecot; do
  invoke-rc.d $i restart || true
done

#DEBHELPER#

#
# Add symlinks for the monit script
# 
monit_dir="/etc/symbiosis/monit.d"
mkdir -p "$monit_dir"

for i in prosody; do
  monit_script="/usr/share/symbiosis/monit/checks/$i"
  link_target="$monit_dir/$i"

  if [ -x "$monit_script" ] && [ ! -e "$link_target" ]; then
    echo "I: Adding symlink for Symbiosis Monit script for $i"
    ln -s "$monit_script" "$link_target" || true
  fi
done

exit 0
