
=head1 NAME

symbiosis-crontab - Execute per-domain crontabs

=cut

=head1 SYNOPSIS

  symbiosis-crontab [args]

  Args:
     --verbose   -  Display verbose information about execution.

=cut


=head1 ABOUT

This script is designed to run non-interactively, it will iterate over
all hosted virtual domains and execute the crontabs which might be present.

As a security measure it is mandatory that a crontab file, located beneath
/srv/example.com/config/crontab is owned by the same Unix UID which owns
/srv/example.com.

For each valid crontab file the B<TODO> ruby script will be launched.

=cut

=head1 BUGS

None known.

=cut

=head1 AUTHOR

 Steve
 --

=cut

=head1 LICENSE

Copyright (c) 2010 by Bytemark Computer Consulting Ltd.
All rights reserved.

This program is free software;
you can redistribute it and/or modify it under
the same terms as Perl itself.
The LICENSE file contains the full text of the license.

=cut
