#!/bin/bash

set -e

#
# Skip, if we are not in "configure" state
#
if [ "$1" != "configure" ]; then
        echo "I: Skipping configuration"
        exit 0
fi

#
#  Remove existing PAMAuthentication setup,
#
find /etc/pure-ftpd/auth/ -lname "*/PAMAuthentication"  -exec rm -f \{\} \;
find /etc/pure-ftpd/auth/ -lname "*/UnixAuthentication" -exec rm -f \{\} \;

#
# Edit our defaults to set it to "standalone"
#
if [ -f /etc/default/pure-ftpd-common ] ; then
  sed -i -e 's/^STANDALONE_OR_INETD=/STANDALONE_OR_INETD=standalone/' /etc/default/pure-ftpd-common
fi

#
# Disable any inetd service
#
if [ -f /etc/inetd.conf -a -x /usr/sbin/update-inetd ] ; then
  update-inetd --disable ftp
  # Don't really care if this errors.
  invoke-rc.d  openbsd-inetd restart || true
fi

##
# SSL cert generation now in symbiosis-common
##

#
#  Link in the certificate if we have one.
#
if [ ! -e /etc/ssl/private/pure-ftpd.pem ]; then
    ln -s /etc/ssl/ssl.combined /etc/ssl/private/pure-ftpd.pem
fi

if [ -e /etc/ssl/private/pure-ftpd.pem ] ; then
  #
  #  TLS should be enabled if we did the linking.
  #
  echo '1' > /etc/pure-ftpd/conf/TLS
fi

#
# Update default runlevels.
#
if [ -x "/etc/init.d/pure-authd" ]; then
  update-rc.d pure-authd defaults >/dev/null
fi

if [ -x "/etc/init.d/pure-ftpd" ]; then
  update-rc.d pure-ftpd defaults >/dev/null
fi

#
#  Restart (or start)
#
if [ "$2" = "" ] ; then
  action=start
else
  action=restart
fi

invoke-rc.d pure-authd $action

#
# Restart pure-ftpd, since we've already made config changes.
#

invoke-rc.d pure-ftpd restart 

#DEBHELPER#
exit 0
