#!/bin/bash
set -e

#
#  Remove the linked certificate if we have one, and the associated TLS file.
#
if [ -L /etc/ssl/private/pure-ftpd.pem ]; then
    rm /etc/ssl/private/pure-ftpd.pem
    rm -f /etc/pure-ftpd/conf/TLS
fi

#
# Remove from the rc levels.
#
if [ "$1" = "purge" ] ; then
  update-rc.d pure-authd remove 
  update-rc.d pure-ftpd remove 
fi

#DEBHELPER#
exit 0
