#!/bin/sh

set -e

if [ "$1" = "upgrade" ]; then
    #
    #  Do nothing for upgrades.
    #
    echo "I: Skipping removal."
    exit 0
fi

#
# Revert the TLS cipher suites
# 
cs="/etc/pure-ftpd/conf/TLSCipherSuite"
if [ -f "$cs" ] && echo "69564370d505ab7968397591929b0bfc  $cs" | md5sum -c > /dev/null 2>&1 ; then
  # OK this is the Debian ciphers
  echo "I: Reverting pure-ftpd cipher suite to Debian default"
  echo 'ALL:!aNULL:!SSLv3' > $cs
fi

#
# Stop the authd
#
invoke-rc.d pure-authd stop

#DEBHELPER#
exit 0
