#!/bin/bash

set -e

if [ "$1" = "upgrade" ]; then
    #
    #  Do nothing for upgrades.
    #
    echo "I: Skipping removal."
    exit 0
fi

#
# Stop the authd
#
if which invoke-rc.d >/dev/null 2>&1; then
    invoke-rc.d pure-authd stop
else
    /etc/init.d/pure-authd stop
fi

#DEBHELPER#
exit 0
