#!/bin/bash

set -e

#
# Skip, if we are not in "configure" state
#
if [ "$1" != "configure" ]; then
    echo "I: Skipping configuration"
    exit 0
fi

#
# Remove the old directory.
#
if [ -d /etc/bytemark-vhost/test.d ]; then
    rm -rf /etc/bytemark-vhost/test.d
fi

#DEBHELPER#
exit 0
